sample_payload: 'sample_payload.json'
DATA_DIR : "./data/"
EXPT_DIR : "./log"
MODEL_DIR : "./models"
CKPT_EXT : '.tar.gz'
exp_name: "Mnist"
LABEL_DIRECTORY: "./data/"



### TRAIN FUNCTION ARGS ###
NUM_INPUT : 784
RAW_IMG_SIZE : (28, 28)
IMG_SIZE : (28, 28)
INPUT_SHAPE : (IMG_SIZE[0], IMG_SIZE[1])
NUM_STEPS: 1000
EPOCHS : 10
BATCH_SIZE: 32
FOLDS : [1]
DISPLAY_STEP: 1
STOPPING_PATIENCE : 32
LR_PATIENCE : 16
INITIAL_LR : 0.1
NUM_CLASSES : 10
CLASSES : [0, 1, 2, 3, 4, 5, 6, 7, 8,9]
CLASSES_STR : ['0', '1', '2', '3', '4', '5', '6', '7','8','9']
MODELNAME: resnet                                                               #### support for [resnet, inception]
