sample_payload: 'sample_payload.json'
EXPT_DIR : "log"
DATA_DIR : "data"
WEIGHTS_DIR : "weights"
exp_name: "reuters-text-classification"

### TRAIN FUNCTION ARGS ###
trainsize: 4659
model: "bert-base-uncased"
dataset: "Reuters"
batch_size: 16
lr: 0.00002
epochs: 7
